version: "3.8"
name: 'user-management'
services:
  db:
    image: postgres:14
    container_name: lb4_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DATA_FOLDER}/postgres:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: lb4_pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - "3001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ${DATA_FOLDER}/pgadmin:/var/lib/pgadmin

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "3002:8080"
